name: Build and deploy my private blog
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Install hugo
        run: |
          sudo apt update
          sudo apt install hugo -y

      - name: Build the blog
        run: hugo --minify
        
      - name: Deploy via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -P ${{ secrets.SSH_PORT }} -r public/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_FOLDER }}
          rm -rf ~./ssh
